Agent subscription
hmrc/income-tax-subscription pull request #80
Opened 2017-04-11 16:13 UTC by suyangyu

added parameter enroluser to ferequest and updated rosm service to call enrolment only if this param is set to true

2017-04-18 09:48 UTC, MJCallahanPage requested changes
One comment re. naming.

2017-04-18 09:48 UTC, MJCallahanPage commented on app/auth/Authenticated.scala
> +  def authenticatedCustom(f: => AuthenticationResult => Future[Result])(implicit hc: HeaderCarrier): Future[Result] = {
What does authenticaatedCustom mean? Is there a better name we can find for this?

2017-04-18 16:52 UTC, MJCallahanPage commented
@suyangyu - can you resolve the expected conflicts please. Thanks

2017-04-19 07:59 UTC, suyangyu commented on app/auth/Authenticated.scala
> +  def authenticatedCustom(f: => AuthenticationResult => Future[Result])(implicit hc: HeaderCarrier): Future[Result] = {
not sure what to call this one, I'm open to suggestions...

Basically in this function you need to pass in a function which you must specify how to deal with the authentication results. Whereas the other function it has default behaviours.

The custom function is solely used for the throttling at the moment so I could call it something along the lines of throttleAuthentication?

2017-04-20 08:09 UTC, MJCallahanPage commented on app/auth/Authenticated.scala
> +  def authenticatedCustom(f: => AuthenticationResult => Future[Result])(implicit hc: HeaderCarrier): Future[Result] = {
Hmmmm, I see. It's a tricky one then.

Leave it as it is then for  now

2017-04-20 08:10 UTC, MJCallahanPage approved these changes

2017-04-20 08:11 UTC, merged